source 'https://rubygems.org'
ruby '2.3.4'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.6'
gem 'redis'
gem 'omniauth-facebook'


gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'sass-rails'
gem 'geokit-rails'
gem 'simple_form'
gem 'uglifier'
gem 'bootstrap-datepicker-rails'
gem 'jquery-ui-rails'
gem 'momentjs-rails'
gem 'country_select'
gem 'webpacker', '~> 3.0'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
