# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9d8c58da3ce07c360f0bd9e4473a01138f9510df296b81ba3bd504e2a26d7b675c6f22b16c848e9f41a953a6252d978a01059d192b9887ef79569dfc816dd2

test:
  secret_key_base: f8b01994286982b707aa41d6e6412fd08fdd160185a61b8a2e6b0ddcb3c91ca3b822612c44607919eb025c60a54397632ecb0720a949098ca8678d1b752e368f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
